language: java
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: "vladpetrovskyi"
    token:
      secure: "PqKqWzvAGmypBMNHVSgc8Y9DrVnZfBJ/rgSLDR18VMJC0X/0WvTWhgfQv7DkD4swbuLofbp/wT2sajCf7zJF85bsUDLZODk68IrTdgk0b37N44QrfVILPmOfajethIznAF2pLjkUdFgTzSKR9U1dd18GzaCtGPk0NjBxbLRN+OhmlpXzZvgpXdzSUy5aDcxkBcfhmTk86br0aqs7jGcG6ESkve+p3eHWY83AVZo8MRVGfdtwErmTecPBeMkzTns96eyc/WaPULpc6DPJEOReb5Z2weHf/VkHJsObGKHIX8p6xaSjgMPWt0rhqv03MiwpKiHbzMzjwXNkCNQEr3LShi2SjUPdaW82HtsEn1JBiGK+2LAKlG7smIkqnXF4NTnBV4nIerhy6gsKvS2RX8l12Dinp0tp8wcRsgv1BKgICXfhL1gecXUPr7oCP9a2m3Hgz0BnqOnlGer4ugd9bhzk56jCbal0SbbWnfXfnfgbdoiGvrk+YzxvtxOkFsYTqzEdr7kwiYmNC/JOc1FUqHRGWHfxRxKwcRNbEQa7KZtr9lhnzD5IoEFn6P2Myi89z/N6X0OH4ohcuyyPjZrlad5X50YMhGtYqrTU5clTUDS8AbU79B7nSjz19GhJnoi7t1GqZXp/kzlM9gWS8sOPxWnEf4Nu2bGvocf3yXMTRHWjJj4="
